### ISSUE TITLE
Broken Pirate Sword

### ISSUE THREAD

**Issue by 6ookie** [RCPisAwesome/RedMRCPWeapons#1]
I try to spawn a Broken Pirate Sword, but it doesn't work. Where I can install the hash for the Sword?

**Comment by RCPisAwesome** [comment]
I think the sword only works with certain peds. In the html file change the button id WEAPON_MELEE_BROKEN_SWORD to the hash without the 0x before it but I still don't think it will work. There are other weapons that don't work either so it might be something else.

**Comment by Z-eus** [comment]
> I try to spawn a Broken Pirate Sword, but it doesn't work. Where I can install the hash for the Sword?

Only works in single player.
